version: "3.9"

services:
  gandyn:
    image: baptistecdr/gandyn:1.0.7@sha256:8a3479591fe99bfbf823d77d2ea39ab51686a669652f4f9345d62dcf33c9db6e
    container_name: gandyn
    environment:
      - TZ=UTC
    volumes:
      - ./config.ini:/config/config.ini
