version: "3.9"

services:
  gandyn:
    image: baptistecdr/gandyn:1.2.0@sha256:0629ee42a7a3ca031cc64ccf55deaa941b4ff2db623ee4a99f7841d7198f2542
    container_name: gandyn
    environment:
      - TZ=UTC
    volumes:
      - ./config.ini:/config/config.ini
